1 task
js-tasks-ru/jsbasic-20240115_user44263 pull request #1
Opened 2024-01-21 08:40 UTC by melihovfa

Implementing Sum Function

2024-01-21 08:40 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2024-01-23 16:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-01-23 17:05 UTC, SinimaWath requested changes

2024-01-23 17:05 UTC, SinimaWath commented on 1-module/1-task/index.js
> +console.log(factorial(n))
Надо убрать эту строчку кода, тесты не проходят

2024-01-24 17:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-01-24 17:32 UTC, SinimaWath approved these changes

2024-01-24 17:33 UTC, merged